server.port=8080
spring.application.name=unidad2-spring-mvc-crud

# Base de datos en memoria para pruebas académicas.
spring.datasource.url=jdbc:h2:mem:unidad2db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.thymeleaf.cache=false
